application: gae-py
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /admin(/|.*\.jhtml)
  script: app.admin.application    

- url: /.*\.jhtml
  script: app.index.application


- url: /images
  static_dir: website/static/images
- url: /javascripts
  static_dir: website/static/javascripts
- url: /stylesheets
  static_dir: website/static/stylesheets

# - url: /images
#   static_dir: static_dir/images
  # http_headers:
    # Access-Control-Allow-Origin: http://mygame.appspot.com



libraries:
- name: webapp2
  version: latest

# - name: jinja2
#   version: 2.6
# - name: setuptools
#   version: 0.6c11


# - url: /user/.*
#   script: user.app
