application: helloworld
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /.*
  script: index.app


# libraries:
# - name: jinja2
#   version: 2.6
# - name: setuptools
#   version: 0.6c11


# - url: /user/.*
#   script: user.app
